name: '0215_gauss_2step' 
# gt_path: 'C:\Users\zzh\MATLAB Drive\DLW-fab\gt_depth'
# lp_path: 'C:\Users\zzh\MATLAB Drive\DLW-fab\lp_data'

lp_file: 'lp1122-1-1225-168-100s.mat'
gt_file: 'gt0213-136-110-1.mat'

# min_dose: 70.0
# max_dose: 140.0


method_phase: 'GS'
optim_params_phase:
  num_iters: 1000
# method_phase: 'SGD'
# optim_params_phase:
#   num_iters: 10000
#   lr: 1.0e-8

method: 'SGD'
optim_params:
  optimizer: 'adam'
  mask_grad_percentage: 1.0
  num_iters: 10000
  eps: 1.0e-6
  amsgrad: True
  lr: 1.0e+14
  lr_s: 0.00001

  
    
loss_params:
  square: False
  normalize: False


prop_model: 'FFT'
normalize_ratio: 1.0 # scaling of target


prop_dist: [50.0e-2]
output_size: [10.0e-2,10.0e-2]
wavelength: [650.0e-9]

pattern_type: 'pic'
pattern_params:
  # Directory for the dataset
  data_path: './data'
  target_filename: 'gauss.jpg'
  rgb: False
  binarize: False
  reverse: False
  contrast_factor: 1.5

# fab_var:
#   # fabrication variations (on gt curve)
#   gamma: [1.0, 1.05, 0.95]
#   amp: [1.0, 1.0, 1.0]
# batch_weight: [1.0,0.5,0.5]

# load checkpoints or not (~)/2D_sgd_0/1D_sgd_0
# load_checkpoint_file: '2D_sgd_0'

refraction_index: [1.62]

# SLM pitch in um
feature_size: [0.5e-6, 0.5e-6]
# feature_size_phase: [2.0e-6, 2.0e-6] # eff. pixel size: for 2-step optimization
# target_res: [400,400] # Target resize res. (can < or > roi_res, corresponding to image pad/crop) 
# roi_res: [450,450] # roi res. of target/simulation when calc. loss
# slm_res: [500,500] # DOE eff res. (eff. pixel size: for 2-step optimization) 
# output_res: [500,500] # phase simulation output res. (must >= roi_res, use interp)

feature_size_phase: [0.5e-6, 0.5e-6] # eff. pixel size: for 2-step optimization
slm_res: [2000,2000] # DOE res.
output_res: [2000,2000] # simulation output res. (must >= roi_res, use interp)
target_res: [500,500] # Target resize res. (can < or > roi_res, corresponding to image pad/crop) 
roi_res: [530,530] # roi res. of target/simulation when calc. loss

save_wrap_res: [6000,6000] 



# use_nonzero_mask: True
# use_zero_mask: False

