name: '0417_grating_6u' 

lp_file: 'lp0328-1-30-110.mat'
# lp_file: 'lp0220-1-super-136-110s.mat'
gt_file: 'gt0411-115-115s.mat'
# min_dose: 30.0

# roi_res can be max_order*2 or max_order*2+1, 
#         which is the number of pixels
# max_order*2 leads to [-max_order, max_order-1]
# max_order*2 leads to [-max_order, max_order]
roi_res: [12,1] 
pattern_params:
  period: 6.0e-6
  order: 1
  # save: False
  # load: True
  save: True
  load: False


feature_size_phase: [0.5e-6, 0.5e-6] # eff. pixel size: for 2-step optimization
save_wrap_res: [6000,6000]
feature_size: [0.5e-6, 0.5e-6]

prop_model: 'FFT'
device: 'cpu'
# method_phase: 'SGD'
# optim_params_phase:
#   lr: 3.0
#   # lr_s: 1.0e-4
#   num_iters: 6000
# method_phase: 'BS'
# optim_params_phase:
  # num_iters: 400
method_phase: 'GS'
optim_params_phase:
  num_iters: 400

method: 'BS'
optim_params:
  num_iters: 800
# method: 'SGD'
# optim_params:
#   lr: 1.0e+8
#   eps: 1.0e-6
#   num_iters: 6000

  
loss_params:
#   use_nonzero_mask: False
#   use_zero_mask: False
  channel_weight: [1.0]
  eff_penalty_weight: 0.0
  square: False
  normalize: False
  custom: 'L1'

loss_params_phase:
#   use_nonzero_mask: False
#   use_zero_mask: False
  channel_weight: [1.0]
  eff_penalty_weight: 0.0
  square: True
  normalize: True

prop_dist: [50.0e-2]
channel_weight: [1.0]

pattern_type: 'grating'
wavelength: [650.0e-9]
refraction_index: [1.29]
# refraction_index: [1.62]
# wavelength: [1550.0e-9]
# refraction_index: [1.6]


# use_zero_mask: True


plot_layout: [1,-1]

