name: '0412_1_grating_10u' 


lp_file: 'lp0328-1-30-110.mat'
# lp_file: 'lp0220-1-super-136-110s.mat'
gt_file: 'gt0406-1-40-110s.mat'
# min_dose: 30.0


# roi_res can be max_order*2 or max_order*2+1
# max_order*2 leads to [-max_order, max_order-1]
# max_order*2 leads to [-max_order, max_order]
roi_res: [20,1] 
pattern_params:
  period: 10.0e-6
  order: 1
  # save: False
  # load: True
  save: True
  load: False
save_wrap_res: [1000,1000]

prop_model: 'FFT'

device: 'cpu'
method: 'SGD'
optim_params:
  lr: 0.24
  num_iters: 6000

# method: 'BS'
# optim_params:
#   num_iters: 800


# loss_params:
#   use_nonzero_mask: False
#   use_zero_mask: False
#   channel_weight: [1.0]
#   penalty_weight: 0.0
#   var_penalty_weight: 0.0

# prop_dist: [50.0e-2]

pattern_type: 'grating'
# wavelength: [1550.0e-9]
# refraction_index: [1.6]
wavelength: [650.0e-9]
# refraction_index: [1.62]
refraction_index: [1.29]
feature_size: [0.5e-6, 0.5e-6]

# use_zero_mask: True


plot_layout: [1,-1]

