name: '0423_1d3_650_e2e' 

lp_file: 'lp0418-2-130-110s.mat'
gt_file: 'gt0423-1-126-110s.mat'


# roi_res: [24,1] # ROI whose inside considers loss
# slm_res: [24,1]
# pattern_params:
#   dim: 1
#   orders: [0,1,2,3,4]
#   order_shift: [0,0] # for 1D, use [shift_value,0]
#   roi_order_num: 5 # ROI which encircles operating orders
#   tot_order_num: 24 # total pixels in width/height
#   save: True
#   load: False
#   # save: False
#   # load: True

roi_res: [16,1] # ROI whose inside considers loss
slm_res: [16,1]
pattern_params:
  dim: 1
  orders: [0,1,2]
  order_shift: [0,0] # for 1D, use [shift_value,0]
  roi_order_num: 3 # ROI which encircles operating orders
  tot_order_num: 16 # total pixels in width/height
  save: True
  load: False
  # save: False
  # load: True

save_wrap_res: [1500,1500]


prop_model: 'FFT'

device: 'cpu'
method: 'SGD'
optim_params:
  lr: 0.15 # 1D
  lr_s: 0.0001
  num_iters: 15000

# method: 'BS'
# optim_params:
#   num_iters: 400

loss_params:
#   use_nonzero_mask: False
#   use_zero_mask: False
  # channel_weight: [1.0]
  eff_penalty_weight: 0.0
  var_penalty_weight: 0.0
  square: True
  normalize: True

# for propagation model
normalize: False

normalize_ratio: 1.0

pattern_type: 'splitter'
# wavelength: [1550.0e-9]
# refraction_index: [1.6]
wavelength: [650.0e-9]
refraction_index: [1.62]
feature_size: [0.5e-6, 0.5e-6]

plot_layout: [1,-1]

