name: '0708_spl4_3u' 


lp_file: 'lp0707-1225-5mm-1k2-150-240-2.mat'
# gt_file: 'gt0707-1225-5mm-1k2-150-260-2.mat'
gt_file: 'gt0709-1225-5mm-1k2-150-290-2.mat'
# min_dose: 70.0


pattern_type: 'splitter_multi'
wavelength: [1500.0e-9,1550.0e-9,1600.0e-9]
refraction_index: [1.6]
feature_size: [0.5e-6, 0.5e-6]

roi_res: [35,35] 
pattern_params:
  orders: [[0,5,10,15], [5,10,15,20], [10,15,20,25]]
  roi_order_num: 30
  tot_order_num: 180
  label: '4pt_3'
  # save: False
  # load: True
  save: True
  load: False

prop_model: 'FFT'

method: 'SGD'
optim_params:
  lr: 0.05
  lr_s: 0.00001
  num_iters: 10000

# method: 'BS'
# optim_params:
#   num_iters: 600


prop_dist: [50.0e-2]


save_wrap_res: [5000,5000]
plot_layout: [1,-1]

